#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
run_example.py
==============
Reproducible example for the TEnKF (Tempered Ensemble Kalman Filter)

This script runs a single assimilation experiment with the reference
configuration used throughout the paper:

    sigma_obs   = 5   (observation error std)
    N_ens       = 20  (ensemble size)
    obs density = 1.0 (all 40 grid points observed)
    alpha       = 2   (tempering scale parameter)
    NTemp       = 2   (number of tempering steps)

The script sweeps the (inflation, localization) grid, the same sweep used to
select the optimal configuration shown in the paper figures, and saves the
results to  data/output/example_result.npz

To reproduce a different condition (different sigma_obs, nens, etc.) just
change the USER PARAMETERS block below.

Usage
-----
    python run_example.py

Requirements
------------
    See environment.yml (Python >= 3.8, numpy, scipy, f2py-compiled modules)
    The Fortran modules must be compiled first:
        cd model/          && bash compile.sh
        cd data_assimilation/ && bash compile.sh
"""


import os

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"


import sys
import numpy as np

# #########################################################
#  Add compiled Fortran module paths
# #########################################################
ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(ROOT, 'fortran', 'model'))
sys.path.insert(0, os.path.join(ROOT, 'fortran', 'da'))

import codes_experiments.sensitivity_conf_default as conf
import codes_experiments.assimilation_letkf_module as alm

# #########################################################
#  USER PARAMETERS  (change these to reproduce other cases)
# #########################################################
OBS_ERR_LABEL  = 'ObsErr5'   # corresponds to sigma_obs = 5
N_ENS          = 20          # ensemble size
OBS_DENSITY    = 1.0         # fraction of grid points observed (1.0 = all 40)
ALPHA_SCALE    = 2           # tempering scale (alpha); larger → more steps
N_TEMP         = 2           # number of tempering pseudo-time steps
OBS_FREQ       = 4           # assimilation frequency (time steps)
EXP_LENGTH     = 10000       # number of assimilation cycles
# #########################################################

# Nature run file (generated by run_nature.py)
den_str       = f'{OBS_DENSITY:.1f}'
nature_name   = f'Paper_Nature_Freq{OBS_FREQ}_Den{den_str}_Type3_{OBS_ERR_LABEL}'
nature_file   = os.path.join(ROOT, 'data', 'Nature', f'{nature_name}.npz')

out_dir       = os.path.join(ROOT, 'data', 'output')
os.makedirs(out_dir, exist_ok=True)
out_file      = os.path.join(
    out_dir,
    f'example_LETKF_{OBS_ERR_LABEL}_Nens{N_ENS}_NTemp{N_TEMP}_alpha{ALPHA_SCALE}.npz'
)

# #########################################################
#  Configure the experiment
# #########################################################
conf.GeneralConf['NatureName'] = nature_name
conf.GeneralConf['ObsFile']    = nature_file

conf.DAConf['NTemp']          = N_TEMP
conf.DAConf['AlphaTempScale'] = ALPHA_SCALE
conf.DAConf['AddaptiveTemp']  = False

conf.DAConf['NEns']       = N_ENS
conf.DAConf['Twin']       = True
conf.DAConf['Freq']       = OBS_FREQ
conf.DAConf['TSFreq']     = OBS_FREQ
conf.DAConf['ExpLength']  = EXP_LENGTH

conf.DAConf['BridgeParam']       = 0.0
conf.DAConf['GrossCheckFactor']  = 1000.0
conf.DAConf['LowDbzPerThresh']   = 1.1

# ######################################################### #
#  (Inflation, Localization) sweep — same grid as the paper #
# ######################################################### #
mult_inf_range  = np.arange(1.0, 1.6, 0.05)   # multiplicative inflation
loc_scale_range = np.arange(0.5, 5.0, 0.5)    # localization half-width

n_inf = len(mult_inf_range)
n_loc = len(loc_scale_range)

total_analysis_rmse = np.zeros((n_inf, n_loc))
total_analysis_sprd = np.zeros((n_inf, n_loc))
total_forecast_rmse = np.zeros((n_inf, n_loc))
total_forecast_sprd = np.zeros((n_inf, n_loc))
NormalEnd           = np.zeros((n_inf, n_loc))

print(f'\n{"="*60}')
print(f'  TEnKF example experiment')
print(f'  sigma_obs={OBS_ERR_LABEL}  Nens={N_ENS}  density={OBS_DENSITY}')
print(f'  NTemp={N_TEMP}  alpha={ALPHA_SCALE}')
print(f'  Sweeping {n_inf} inflation x {n_loc} localization values')
print(f'{"="*60}\n')

total_iters = n_inf * n_loc
for iinf, mult_inf in enumerate(mult_inf_range):
    for iloc, loc_scale in enumerate(loc_scale_range):
        iteration = iinf * n_loc + iloc + 1
        print(f'  [{iteration:3d}/{total_iters}]  inf={mult_inf:.2f}  loc={loc_scale:.1f}',
              flush=True)

        conf.DAConf['InfCoefs']        = np.array([mult_inf, 0.0, 0.0, 0.0, 0.0])
        conf.DAConf['LocScalesLETKF']  = np.array([loc_scale, -1.0])
        conf.DAConf['LocScalesLETPF']  = np.array([loc_scale, -1.0])

        result = alm.assimilation_letkf_run(conf)

        NormalEnd[iinf, iloc]           = result['NormalEnd']
        total_analysis_rmse[iinf, iloc] = np.mean(result['XASRmse'])
        total_forecast_rmse[iinf, iloc] = np.mean(result['XFSRmse'])
        total_analysis_sprd[iinf, iloc] = np.mean(result['XASSprd'])
        total_forecast_sprd[iinf, iloc] = np.mean(result['XFSSprd'])

# ######################################################### #
#  Save results                                             #
# ######################################################### #
np.savez_compressed(
    out_file,
    NormalEnd=NormalEnd,
    mult_inf_range=mult_inf_range,
    loc_scale_range=loc_scale_range,
    total_analysis_rmse=total_analysis_rmse,
    total_forecast_rmse=total_forecast_rmse,
    total_analysis_sprd=total_analysis_sprd,
    total_forecast_sprd=total_forecast_sprd,
    # Experiment metadata
    obs_err_label=OBS_ERR_LABEL,
    n_ens=N_ENS,
    obs_density=OBS_DENSITY,
    alpha_scale=ALPHA_SCALE,
    n_temp=N_TEMP,
)

print(f'\n  Results saved to: {out_file}')
print(f'  Best analysis RMSE: {np.nanmin(total_analysis_rmse):.4f}')
print(f'\n{"="*60}\n')
